<?xml version="1.0"?>
<testsuites>
<testsuite name="Root Suite" timestamp="2021-06-29T15:41:34" tests="0" file="cypress/integration/firstTest.spec.js" time="0.0000" failures="0"></testsuite>
<testsuite name="Test with backend" timestamp="2021-06-29T15:41:34" tests="5" time="14.3510" failures="0">
  
  <testcase name="Test with backend verify correct request and response" time="5.6120" classname="verify correct request and response"></testcase>
  
  <testcase name="Test with backend intercepting and modifying the request and response" time="3.2470" classname="intercepting and modifying the request and response"></testcase>
  
  <testcase name="Test with backend should gave tags with routing object" time="1.0880" classname="should gave tags with routing object"></testcase>
  
  <testcase name="Test with backend delete a new article in a global feed" time="4.4040" classname="delete a new article in a global feed"></testcase>
  
</testsuite>

<testsuite name="Root Suite" timestamp="2021-06-29T15:41:49" tests="0" file="cypress/integration/secondTest.spec.js" time="0.0000" failures="0"></testsuite>
<testsuite name="Test log out" timestamp="2021-06-29T15:41:49" tests="1" time="0.0000" failures="1">
  
  <testcase name="Test log out verify use can log out successfully" time="0.0000" classname="verify use can log out successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress/integration/secondTest.spec.js:107:27)]]></failure>
    
  </testcase>
  
</testsuite>

</testsuites>